### ISSUE TITLE
Pre-Publication and Post-Publication tabs

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#10]
This one is just an idea, not a definitely proposal ...

Would it make sense to have "Before Publication" and "After Publication" tabs. Already we can't move statuses between them. This would make it very clear that these are different processes

We are already proposing the remove the "Add New" and "Settings" tabs:
<img width="554" alt="Screenshot 2023-04-26 at 10 31 02 AM" src="https://user-images.githubusercontent.com/3868028/234608561-2293f9a0-fc6d-4f6b-9a6b-edb9e6c10934.png">

**Comment by agapetry** [comment]
59b517cf8f3110f6d016206979fd13c8e1f64ae0
31d54a09c36166d74e108425d610a0dfc51d3a7f
1b9cc504d7811fd1cc990f258e6c6031187e5410
39610a662f961c67c10670902d798a846f514fea
