### ISSUE TITLE
Make "Add New" into WordPress standard button

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#11]
Can we make "Add New" into a WordPress standard button up by the title?
<img width="617" alt="Screenshot 2023-04-26 at 10 32 02 AM" src="https://user-images.githubusercontent.com/3868028/234608985-1b42483c-0e79-4713-90cf-fbc62ea714d6.png">

**Comment by agapetry** [comment]
59b517cf8f3110f6d016206979fd13c8e1f64ae0
39610a662f961c67c10670902d798a846f514fea
