### ISSUE TITLE
Automatically check the "Pending Review" boxes for Authors etc

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Statuses#111]
I think these should be enabled and greyed out for Editors, Authors, and Contributors, or perhaps this should just be hidden entirely, as with Draft

![Screenshot 2024-01-04 at 8 08 18 AM](https://github.com/publishpress/publishpress-statuses/assets/3868028/78f7175d-a5ec-468c-9ea2-61b2faf4b73f)

Here's an example with an Author user. Their box for "Pending Review" isn't checked, but WordPress gives them access by default:
![Screenshot 2024-01-04 at 8 09 09 AM](https://github.com/publishpress/publishpress-statuses/assets/3868028/2b7f1e02-7158-4a05-b910-f64ab2167d15)

**Comment by agapetry** [comment]
WordPress 6.6 obsoletes this issue by removing the Pending review checkbox.
