### ISSUE TITLE
"share capabilities with another status."

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#112]
Is this description valid? "share capabilities with another status."
![Screenshot 2024-01-04 at 8 18 13 AM](https://github.com/publishpress/publishpress-statuses/assets/3868028/59e6e742-51cc-4617-8bcf-e16fdbaf8cd0)

**Comment by agapetry** [comment]
@stevejburge Yes, that has been a supported configuration with the Status Control module of Permissions Pro for several years.

**Comment by stevejburge** [comment]
Ok, thanks @agapetry
