### ISSUE TITLE
It seems impossible for me to add personalized statuses to my Custom Post Types

### ISSUE THREAD

**Issue by mieumieu10** [publishpress/publishpress-statuses#118]
Hello there, I just updated the plugin, and I had to add Publishpress statuses, the plugin detects the old defined statuses, but when I try to add my CPT in the settings (PublishPress Statuses Settings page) but when I save the checked box is unchecked automatically.
I use the PODS plugin for my custom post types, is it possible to force the use of statuses?

![Screenshot 2024-01-06 at 12 11 57](https://github.com/publishpress/publishpress-statuses/assets/88109926/c3144a16-600b-49a6-b161-5f1afb7b8647)
when I try to edit a status there is the option all post types and post, none of my CPTs are displayed here, even if all post types is checked nothing happens.

**Comment by stevejburge** [comment]
Thanks @mieumieu10 

I can confirm this, @agapetry. The "Use on these post types" setting isn't saving when I select custom post types

![Screenshot 2024-01-06 at 9 18 39 AM](https://github.com/publishpress/publishpress-statuses/assets/3868028/4dc72955-f841-4987-8410-bea75be8d09f)

**Comment by stevejburge** [comment]
Solved in a recent update
