### ISSUE TITLE
Publish button stays Publish on Classic Editor

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/publishpress-statuses#119]
![image](https://github.com/publishpress/publishpress-statuses/assets/83811723/2a28e1e4-4f03-4c07-b384-6fd5f5692d7a)

The button "Publish" should change to "Update" if the post published. 

This happens on Classic editor

**Comment by agapetry** [comment]
@rizaardiyanto1412 What version are you seeing this with?

**Comment by rizaardiyanto1412** [comment]
@agapetry It was 1.0.2.4.

But I still see it in 1.0.3.5 
https://www.loom.com/share/6563d30277184242bca0a37627a0368c

**Comment by stevejburge** [comment]
Fixed in a recent version
