### ISSUE TITLE
Visual indicator that indenting is possible

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#120]
Let's add a visual indicator that indenting is possible. I didn't realize it until talking with Kevin:
![Screenshot 2024-01-08 at 11 39 06 AM](https://github.com/publishpress/publishpress-statuses/assets/3868028/3cd3f8c7-67ae-4b78-92ab-4d9542783ba3)

**Comment by agapetry** [comment]
Solved in a recent version
