### ISSUE TITLE
Think carefully about the text in the "Pre-Publication" area

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#121]
Let's think really carefully about these labels so people understand them clearly

For example, how about these?

- Old: Pre-Publication Workflow Sequence
- New: Main Workflow

- Old: Manually Selectable Pre-Publication Statuses
- New: Alternate Workflows
![Screenshot 2024-01-08 at 11 40 10 AM](https://github.com/publishpress/publishpress-statuses/assets/3868028/83b6db54-2b6d-4d56-9264-59a35b345207)

**Comment by agapetry** [comment]
Solved in a recent version
