### ISSUE TITLE
Define some sample Alternate Workflows

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#122]
Let's include a couple of sample statuses for the Alternate Workflows area. How about something like this?

- Rejected: This Post is not suitable for publication.
- Postponed: This Post has been delayed for now.

Maybe we could also include an indented example in the Disabled area?

**Comment by stevejburge** [comment]
Some examples from Kevin. I like the direction but might try to brainstorm something more generic than Science Committee etc

![image](https://github.com/publishpress/publishpress-statuses/assets/3868028/73c4ffbe-5b9e-45a9-9480-a961f7dd802a)

**Comment by agapetry** [comment]
Solved in a recent version
