### ISSUE TITLE
Small text changes in settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#128]
Old: Workflow sequence
New: Main Workflow sequence

Old: De-clutter the dropdown by hiding statuses outside current branch (if defaulting by sequence and some statuses are nested)
New: I'm not quite sure how to explain this. Let's talk

Old: Editor capabilities
New: I'm not quite sure how to explain this. Let's talk
![Screenshot 2024-01-09 at 12 59 48 PM](https://github.com/publishpress/publishpress-statuses/assets/3868028/32efa17c-e68d-4d0f-a0ca-f9796be84e67)

**Comment by agapetry** [comment]
@steve does this help?

![image](https://github.com/publishpress/publishpress-statuses/assets/43488774/42d64681-2683-451a-9985-17a0c0de89c5)

**Comment by agapetry** [comment]
The Workflow guidance is actually not just for the main workflow. It also applies to alternate workflows that are nested.

**Comment by stevejburge** [comment]
@agapetry Thanks. How about this:

"De-clutter the dropdown in the post editing screen. If you are using nested statuses, this will hide statuses outside the current workflow branch."

I'm not 100% sure I understand this one yet:
"PublishPress Permissions integration. The Supplemental Role of Editor covers custom statuses"

**Comment by agapetry** [comment]
Solved in a recent version
