### ISSUE TITLE
 Drop the arrows to hide sections

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#13]
I think these arrows might cause more confusion than it solves, plus it's not a common option in WordPress:

<img width="654" alt="Screenshot 2023-04-26 at 10 49 12 AM" src="https://user-images.githubusercontent.com/3868028/234614223-74bb5b3f-12fe-4d15-87b5-a049cea36492.png">

**Comment by agapetry** [comment]
31d54a09c36166d74e108425d610a0dfc51d3a7f
1b9cc504d7811fd1cc990f258e6c6031187e5410
5165314533a9d16e786999be1b3c485ebe25b103
