### ISSUE TITLE
Does indent work for the Main Worklow?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#132]
I don't see this reflected in the post editing screen's statuses dropdown
![Screenshot 2024-01-12 at 3 02 56 PM](https://github.com/publishpress/publishpress-statuses/assets/3868028/7f7a5e86-dd61-4b07-950f-3a5c03429262)

Here's how that appears:

![Screenshot 2024-01-12 at 3 04 09 PM](https://github.com/publishpress/publishpress-statuses/assets/3868028/2712b465-cb5a-4e1e-b8e7-1269df17aefd)

**Comment by agapetry** [comment]
@stevejburge If you have the Workflow settings defaulting to next status and "Declutter status dropdown" enabled, this is how it's supposed to work. The child statuses are hidden from the dropdown until after you select the parent status.

**Comment by stevejburge** [comment]
Ah, that makes sense, thanks. Will follow up here https://github.com/publishpress/publishpress-statuses/issues/128
