### ISSUE TITLE
Error on /PlannerImport.php on line 313

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#138]
![Screenshot 2024-01-18 at 3 07 34 PM](https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/6f992f7c-0f8b-4900-9155-2081220dd484)

**Comment by olatechpro** [comment]
@stevejburge I transferred this issue to Statuses repository because it's from the file but noticed you already created another one https://github.com/publishpress/publishpress-statuses/issues/137

So, closing this
