### ISSUE TITLE
Small issue with Statuses and Checklists together

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#139]
When Statuses and Checklists and are used together, the pre-publish panel doesn't work
![Screenshot 2024-01-23 at 10 13 39 AM](https://github.com/publishpress/publishpress-statuses/assets/3868028/0b7973a3-bb79-41bc-b2a4-d8959d60e91e)

**Comment by agapetry** [comment]
Solved in a recent version
