### ISSUE TITLE
Only one alternate workflow?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#14]
Is it only possible to add one alternate workflow?
<img width="665" alt="Screenshot 2023-04-26 at 10 50 10 AM" src="https://user-images.githubusercontent.com/3868028/234614544-f24161b2-6f10-429e-bacf-632b2afc7cea.png">

**Comment by agapetry** [comment]
59b517cf8f3110f6d016206979fd13c8e1f64ae0
39610a662f961c67c10670902d798a846f514fea
