### ISSUE TITLE
Add filter for button text

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Statuses#184]
If PublishPress Statuses active, the button will show "Workflow"

Can we have a filter so user can modify it for example "Publish". 

Or maybe another solution?

Original request: https://secure.helpscout.net/conversation/2564874074/221562?viewId=6932143

**Comment by agapetry** [comment]
@rizaardiyanto1412 The filter "presspermit_workflow_button_label" is applied for that purpose:

https://github.com/publishpress/PublishPress-Statuses/blob/88fda6fd635700e45bdf6d891a9704eb91bfa5b1/PostEditGutenbergStatuses.php#L116
