### ISSUE TITLE
Issue with statuses: permalink doesn't update with change of post title

### ISSUE THREAD

**Issue by arzu-poolie** [publishpress/PublishPress-Statuses#185]
Hi everyone,

we've got a issue with custom statuses. There are two custom statuses we've added via the publishpress Plugin.

The following happens:
- I open a new post (status is standard "Draft" from WordPress) and add a title "A"
- Permalink says "/a/"
- I change the status to a custom status from publishpress
- I change the post title to "B"
- permalink doesn't update and stays "A"

This is quite annoying because the editing team needs to check the post title AND needs to update the permalink manually, which costs time and a lot of awareness.

Is there any trick to it oder is this something that needs to be fixed? The editing team says that it worked in the past.

Thanks in advance!

**Comment by stevejburge** [comment]
Sorry, this kind of question is best deal with via our Free or Pro support
