### ISSUE TITLE
Redirect to Statuses screen after plugin activation

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Statuses#191]
https://make.wordpress.org/core/2024/05/24/wordpress-6-5-4-an-upcoming-maintenance-release/

We should redirect new users to the "Statuses" screen

**Comment by agapetry** [comment]
@stevejburge Are you seeing something in that 6.5.4 comment thread that's instructive on how to best implement this?

**Comment by stevejburge** [comment]
Thanks @agapetry. Maybe we can ignore that thread and just add a redirect as we have in our other plugins.

For example, Authors does this:

   public function redirect_on_activate()
        {
            if (get_option('ppma_activated')) {
                delete_option('ppma_activated');
                wp_redirect(admin_url("edit-tags.php?taxonomy=author&welcome"));
                exit;
              }
