### ISSUE TITLE
Prepare for WordPress 6.6

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Statuses#192]
There are some noticeable changes around the way Statuses work in 6.6. For example, in the sidebar:

![Screenshot 2024-06-11 at 4 28 07 PM](https://github.com/publishpress/PublishPress-Statuses/assets/3868028/49f0e210-5655-47a4-a5cf-8aa34e3a18c9)

**Comment by stevejburge** [comment]
@agapetry I wondered if the Statuses plugin should disable that option. It doesn't contain any statuses from our plugin

**Comment by agapetry** [comment]
I'll give some thought to an expedient way to clear up the apparent redundancy. We do still need the Unpublished / Published / Password Protected toggle function of the built-in status selector.

**Comment by stevejburge** [comment]
Thanks. This is a nice-to-have, not an essential change
