### ISSUE TITLE
Add an option to hide the default status dropdown

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Statuses#206]
Let's add an option (enabled by default) to hide this

I think most admins will want to prevent users from moving content to Private or password-protected

![Screenshot 2024-09-11 at 12 27 10 PM](https://github.com/user-attachments/assets/05b475a2-8f6c-4a40-a4f0-0e704269293d)

**Comment by agapetry** [comment]
@stevejburge Do you still see this as an issue, considering that the link is already suppressed if the user does not have publishing capability?

**Comment by stevejburge** [comment]
@agapetry In that case, I'm happy to skip this and revisit if any users raise the topic
