### ISSUE TITLE
Prepare for WordPress.org

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#37]
The WP repo team now recommend this plugin before we submit: https://wordpress.org/plugins/plugin-check/

**Comment by agapetry** [comment]
The remaining task is to migrate away form base64 encoding of status properties, instead using the term_meta table.

**Comment by agapetry** [comment]
8402fbf8853128dce0ac28ed5fbf85b04743a0f7

**Comment by agapetry** [comment]
Current code scan status:

- Plugin check shows only the Contributors warning
- Our standard phpcs scan shows only 3 warnings:

![image](https://github.com/publishpress/publishpress-statuses/assets/43488774/73eabaf3-b691-45b3-9175-10fd1eaa4d08)
