### ISSUE TITLE
Post Status dropdown: Safari won't hide option

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#66]
This is the Statuses dropdown in Safari:

<img width="453" alt="Screenshot 2023-10-18 at 3 13 38 PM" src="https://github.com/publishpress/publishpress-statuses/assets/3868028/fc76ff0e-3b9d-409a-a1e5-668dafbbf057">

**Comment by agapetry** [comment]
This is a Safari issue that we don't have an easy fix for. In the current implementation, there needs to be a hidden item in that dropdown to distinguish between a default submission and manual selection of the Pending status.  But Safari does not fully honor the hiding of a dropdown item.

**Comment by htmgarcia** [comment]
@agapetry the `<option>` is hidden with inline CSS?

**Comment by andergmartins** [comment]
Maybe we could chance the strategy by usina `optgroup` instead?

**Comment by agapetry** [comment]
@htmgarcia It's hidden by jQuery:

`// Blank option for Safari, which cannot hide it`
 `$('div.publishpress-extended-post-status select option[value="pending"]').html('').hide();`

**Comment by agapetry** [comment]
> @agapetry Maybe we could change the strategy by using `optgroup` instead, to separate items

@andergmartins Do you mean Safari would let me hide an optgroup?
