### ISSUE TITLE
Disable Manually Selectable by default

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#71]
Can we disable this option and have it only available via a Setting? 

It's not clear what it does
![Screenshot 2023-11-29 at 7 31 58 PM](https://github.com/publishpress/publishpress-statuses/assets/3868028/91128500-f053-4af8-81a7-2b7849afaff6)

**Comment by agapetry** [comment]
@stevejburge That's where newly defined statuses go by default.  The sequence is to create a status, then drag it to the desired workflow sequence.

**Comment by agapetry** [comment]
@stevejburge Disabling that by default would effectively trash a significant aspect of the workflow control mechanism by burying it in a setting that most users will not discover.

**Comment by stevejburge** [comment]
@agapetry OK, thanks. Let me think again about this then. 

Perhaps we can tweak the title and the UI to make this clearer.

**Comment by agapetry** [comment]
This should be reconsidered in light of the drop targets and captions in v1.0.2
![image (5)](https://github.com/publishpress/publishpress-statuses/assets/43488774/1d3336ee-3dda-4d8d-88c5-a8934666fe35)

**Comment by agapetry** [comment]
Solved in a recent version
