### ISSUE TITLE
Label for "Manually Selectable Pre-Publication Statuses"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#77]
Can we tweak the text? Sorry, it's still not clear to me what this area does

![Screenshot 2023-12-14 at 10 45 14 AM](https://github.com/publishpress/publishpress-statuses/assets/3868028/66e723f0-02a6-467f-84b6-b4850c704fe1)

**Comment by agapetry** [comment]
@stevejburge One of the plugin's features is a guided editing progression, where the status selection defaults to the next status in the workflow.

However, some users will want to define statuses that are selectable but not selected by default / automatically.  That's what this section is for.  If statuses in this section are nested, the default editing progression will treat it as an alternate publication workflow, with status selection defaulting to the next status in this alternate sequence.

Can you suggest text to make that more clear without being overly verbose? We've been at odds over describing this for a long time.

**Comment by agapetry** [comment]
@stevejburge Also, even if "Default to Next Status" is not enabled, statuses in the "Manually Selectable" section are displayed lower in the status dropdown.

**Comment by agapetry** [comment]
Solved in a recent version
