### ISSUE TITLE
Edit Status: Capabilities / Permissions Pro - Can't set Post Access to "Default Capabilities"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#79]
If you choose "Custom Capabilities for this Status" it doesn't appear possible to move it back to default
![Screenshot 2023-12-14 at 12 21 08 PM](https://github.com/publishpress/publishpress-statuses/assets/3868028/2f6b5e75-2b0d-4f49-931b-cecac1149377)

**Comment by agapetry** [comment]
@stevejburge Thanks. I was able to add a fix for that in the status-capabilities library (Permissions Pro and Capabilities Pro).
