### ISSUE TITLE
Cannot disable all statuses for all post types

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#80]
It looks like Statuses is active immediately on Posts and Pages, but these are set to empty:
![Screenshot 2023-12-14 at 12 22 53 PM](https://github.com/publishpress/publishpress-statuses/assets/3868028/20b41624-b718-4c85-9439-0ee3feb9cf24)

**Comment by agapetry** [comment]
@stevejburge I'm not seeing the originally reported symptoms with 1.0.2.1 on a fresh instawp test site.

Post types default to both Posts and Pages, and I can disable statuses for either.

What I do see is that I cannot disable for all post types.  Trying to do so results in a Posts-only setting.  That's technically a bug, but what would be the actual purpose of having the plugin active, yet fully disabled for all post types?

**Comment by stevejburge** [comment]
@agapetry OK, I can confirm this fix on a new site

In a future release, let's allow people to disable all options

They may need to do it for testing

**Comment by agapetry** [comment]
Solved in a recent version
