### ISSUE TITLE
Disabled visibility statuses are showing

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#83]
![Screenshot 2023-12-14 at 12 32 25 PM](https://github.com/publishpress/publishpress-statuses/assets/3868028/775b8256-3227-4e19-afa7-e628e3388b95)
![Screenshot 2023-12-14 at 12 35 08 PM](https://github.com/publishpress/publishpress-statuses/assets/3868028/fd3b5324-2787-4259-8b0f-0785bd0ef731)

**Comment by agapetry** [comment]
@stevejburge Thanks. I was able to diagnose and fix this.
