### ISSUE TITLE
Non-Administrator login causes Auto Draft publication

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-statuses#87]
I'm editing a post with an Author who is not able to publish a post. The Auto Drafts for this Author are being saved a new posts:

![Screenshot 2023-12-18 at 2 18 33 PM](https://github.com/publishpress/publishpress-statuses/assets/3868028/03abac2f-bd45-4001-bc8e-e81a6a282944)

**Comment by agapetry** [comment]
@stevejburge This is with Statuses as the only active plugin?

**Comment by stevejburge** [comment]
Yes, plus Capabilities for the user testing
